spring:
  redis:
    host: 192.168.236.132
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: -1



