server:
  port: 9092

springfox:
  documentation:
    auto-startup: false
    enabled: false
    open-api:
      enabled: false
    swagger-ui:
      enabled: false
    swagger:
      v2:
        enabled: false
        use-model-v3: false